### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by chawdamrunal** [GerbenJavado/LinkFinder#76] opened 2020-06-08 19:23 UTC
Error: invalid input defined or SSL error: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:852)>

**Comment by EdOverflow** [comment] 2020-06-09 09:46
Duplicate of #42.

**Closed by EdOverflow** 2020-06-09 09:46 UTC
